spring:
  profiles:
    active: local
  messages:
    basename: messages
    encoding: UTF-8

integration:
  rabbit:
    exchanges:
      analytics: analytics-exchange
    queues:
      inbound:
        tg-bot:
          request: analytics-request-queue
      outbound:
        tg-bot:
          pulse: analytics-response-pulse-queue
          news: analytics-response-news-queue
    routing-keys:
      tg-bot:
        request: request
        response:
          pulse: response.pulse
          news: response.news