server:
  port: 8084

security:
  internal:
    token: Iq6Vu8Nz7Xa3Rl9Cm5YbTc2WpDf4Oj5ZfGn1Kh3
  tinkoff:
    # Paste your tinkoff-invest token for test this service
    token: t.g9aFxv3WRSvVqt4MPfhruN1nB2jW1vJM5fKBvYWB9ypGItMYfj0IhPb-lUA2j3ac8qkvj_niNzL_iVpbjnvSvw

integration:
  rest:
    tinkoff-api-service-url: http://localhost:8082
    finam-news-rss-url: https://www.finam.ru/analysis/conews/rsspoint/
  pulse:
    brands-info-url: https://www.tbank.ru/api/trading/symbols/brands?sessionId=bQNqf8OaUMb35kPn0LvAtX3QwMFoO7zC.m1-prod-api-138&appName=web&appVersion=1.480.0&origin=web
    stock-news-url: https://www.tbank.ru/api/invest-gw/social/post/feed/v1/feed?sessionId=29II0ESsZFHp6qT3IkFgwkpVuJQcEfWB.m1-prod-api-138&appName=invest&appVersion=1.480.0&origin=web&platform=web&limit=9999999
    stock-ideas-url: https://www.tbank.ru/api/invest/smartfeed-public/v1/feed/api/ideas?sessionId=1DODhdaBBHo63oINhpMXVlbKL60fMp7h.m1-prod-api-138&appName=web&appVersion=1.479.0&origin=web&limit=100&ticker=
    news-page-url: https://www.tbank.ru/invest/social/profile/
    idea-page-url: https://www.tbank.ru/invest/ideas/

logging:
  level:
    feign: DEBUG