server:
  port: 8084

security:
  internal:
    token: Iq6Vu8Nz7Xa3Rl9Cm5YbTc2WpDf4Oj5ZfGn1Kh3
  tinkoff:
    # Paste your tinkoff-invest token for test this service
    token:

integration:
  rest:
    tinkoff-api-service-url: http://localhost:8082

logging:
  level:
    feign: DEBUG