apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-analytics-service
spec:
  selector:
    app: lissa-trading-analytics-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP